name:               pomc
version:            2.1.0
synopsis:           A model-checking tool for POTL
description:        A model-checking tool for POTL
category:           Formal methods

author:             Davide Bergamaschi, Michele Chiari and Francesco Pontiggia
maintainer:         michele.chiari@polimi.it

copyright:          2020-2023 Davide Bergamaschi, Michele Chiari and Francesco Pontiggia
license:            MIT
license-file:       COPYING.md

extra-source-files:
- README.md

dependencies:
- base >= 4.11 && < 5

library:
  source-dirs:      src
  exposed-modules:
  - Pomc.Check
  - Pomc.Opa
  - Pomc.Potl
  - Pomc.Prec
  - Pomc.Prop
  - Pomc.Satisfiability
  - Pomc.ModelChecker
  - Pomc.Parse.Parser
  - Pomc.Parse.MiniProc
  - Pomc.OpaGen
  - Pomc.MiniProc
  - Pomc.MiniIR
  - Pomc.TimeUtils
  - Pomc.Prob.ProbModelChecker
  - Pomc.Prob.MiniProb
  - Pomc.Prob.ProbUtils
  ghc-options:
  - -Wall
  - -O2
  dependencies:
  - bv
  - containers
  - mtl
  - deepseq
  - megaparsec
  - parser-combinators
  - text
  - vector
  - hashable
  - hashtables
  - unordered-containers
  - random
  - filepath
  - z3
  - scientific

executables:
  pomc:
    main:           Main.hs
    source-dirs:    app
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-H
    - -Wall
    - -O2
    dependencies:
    - pomc
    - filepath
    - megaparsec
    - text
    - containers
    - cmdargs

internal-libraries:
  pomc-tests:
    source-dirs:    test
    ghc-options:
    - -Wall
    - -O2
    dependencies:
    - pomc
    - containers
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-bench
    - raw-strings-qq
    - megaparsec
    - text

tests:
  test-pomc:
    main:           Test.hs
    source-dirs:    test/test
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-H
    - -Wall
    - -O2
    - -threaded
    dependencies:
    - pomc-tests
    - tasty

benchmarks:
  bench-pomc:
    main:           Bench.hs
    source-dirs:    test/bench
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-H
    - -Wall
    - -O2
    dependencies:
    - pomc-tests
    - tasty-bench
