name:               oppas
version:            3.1.0
synopsis:           A tool suite for verifying recursive (probabilistic) programs.
description:        >-
  OPPAS contains two tools. POMC, for verifying recursive programs,
  and POPACheck, for probabilistic programs.
category:           Formal methods

author:             Davide Bergamaschi, Michele Chiari and Francesco Pontiggia
maintainer:         michele.chiari@tuwien.ac.at

copyright:          2020-2025 Davide Bergamaschi, Michele Chiari and Francesco Pontiggia
license:            MIT
license-file:       COPYING.md

extra-source-files:
- README.md

dependencies:
- base >= 4.11 && < 5

library:
  source-dirs:      src
  exposed-modules:
  - Pomc.Check
  - Pomc.Opa
  - Pomc.Potl
  - Pomc.Prec
  - Pomc.Prop
  - Pomc.Satisfiability
  - Pomc.ModelChecker
  - Pomc.Parse.Parser
  - Pomc.Parse.MiniProc
  - Pomc.OpaGen
  - Pomc.MiniProc
  - Pomc.MiniIR
  - Pomc.TimeUtils
  - Pomc.LogUtils
  - Pomc.Z3Encoding
  - Pomc.Prob.ProbModelChecker
  - Pomc.Prob.MiniProb
  - Pomc.Prob.ProbUtils
  ghc-options:
  - -Wall
  - -Wno-incomplete-patterns
  - -Wno-incomplete-uni-patterns
  - -Wno-orphans
  - -O2
  dependencies:
  - bv
  - containers
  - mtl
  - transformers
  - deepseq
  - megaparsec
  - parser-combinators
  - text
  - vector
  - hashable
  - hashtables
  - unordered-containers
  - random
  - filepath
  - z3
  - monad-logger
  - scientific
  - integer-logarithms
  - witch
  - strict-containers
  - hmatrix

executables:
  pomc:
    main:           Main.hs
    source-dirs:    pomc
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-H
    - -Wall
    - -O2
    dependencies:
    - oppas
    - megaparsec
    - text
    - containers
    - cmdargs
    ld-options: -Wl,-rpath -Wl,$ORIGIN/lib
  popacheck:
    main:           Main.hs
    source-dirs:    popacheck
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-H
    - -Wall
    - -O2
    dependencies:
    - oppas
    - filepath
    - megaparsec
    - text
    - containers
    - cmdargs
    ld-options: -Wl,-rpath -Wl,$ORIGIN/lib

internal-libraries:
  pomc-tests:
    source-dirs:    test
    ghc-options:
    - -Wall
    - -O2
    dependencies:
    - oppas
    - containers
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-bench
    - raw-strings-qq
    - megaparsec
    - text

tests:
  test-pomc:
    main:           Test.hs
    source-dirs:    test/test
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-H
    - -Wall
    - -O2
    - -threaded
    dependencies:
    - pomc-tests
    - tasty

benchmarks:
  bench-pomc:
    main:           Bench.hs
    source-dirs:    test/bench
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-H
    - -Wall
    - -O2
    dependencies:
    - pomc-tests
    - tasty-bench
