name:               pomc
version:            2.1.0
synopsis:           A model-checking tool for POTL
description:        A model-checking tool for POTL
category:           Formal methods

author:             Davide Bergamaschi, Michele Chiari and Francesco Pontiggia
maintainer:         michele.chiari@polimi.it

copyright:          2020-2023 Davide Bergamaschi, Michele Chiari and Francesco Pontiggia
license:            MIT
license-file:       COPYING.md

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:      src
  exposed-modules:
  - Pomc.Check
  - Pomc.Opa
  - Pomc.Potl
  - Pomc.Prec
  - Pomc.Prop
  - Pomc.Satisfiability
  - Pomc.ModelChecker
  - Pomc.Parse
  - Pomc.OpaGen
  - Pomc.MiniProc
  - Pomc.MiniProcParse
  - Pomc.Util
  - Pomc.Z3Encoding
  ghc-options:
  - -Wall
  - -O2
  dependencies:
  - bv
  - containers
  - criterion-measurement
  - deepseq
  - megaparsec
  - parallel
  - parser-combinators
  - text
  - vector
  - mtl
  - hashable
  - hashtables
  - unordered-containers
  - random
  - filepath
  - z3

executables:
  pomc:
    main:           Main.hs
    source-dirs:    app
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-H
    - -Wall
    - -O2
    dependencies:
    - pomc
    - filepath
    - megaparsec
    - text
    - containers
    - cmdargs

tests:
  test-pomc:
    main:           Test.hs
    source-dirs:    test
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-H
    - -Wall
    - -O2
    - -threaded
    dependencies:
    - pomc
    - containers
    - deepseq
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - hashable
    - unordered-containers
    - raw-strings-qq
    - megaparsec
    - text
